# Generated by Django 4.2.6 on 2023-10-12 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_alter_posts_content_alter_posts_publisheddate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
    ]
