# Generated by Django 4.2.6 on 2023-10-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_alter_posts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='publishedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
